@port=3000
@host=http://localhost:{{port}}

### GET /
GET {{host}}

### Get all employees
GET {{host}}/employees

### Get specific employee
GET {{host}}/employees/2

### Get nonexistent employee
GET {{host}}/employees/123

### Get random employee
GET {{host}}/employees/random